plugins:
  dep_proxy:
    executor: central_deployment_agent
    source: https://github.com/cloudify-incubator/cloudify-deployment-proxy-plugin/archive/v1.0.0.zip

data_types:

  cloudify.datatypes.Deployment:
    properties:
      outputs:
        description: >
          A dictionary of "{ key: value, key: value }".
          Get "key" the deployment.
          Set "value" runtime property to the value of the output.
        required: false

node_types:

  cloudify.nodes.DeploymentProxy:
    derived_from: cloudify.nodes.Root
    properties:
      use_external_resource:
        type: boolean
        default: true
      resource_id:
        type: string
        description: The deployment ID.
        required: true
      resource_config:
        type: cloudify.datatypes.Deployment
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: dep_proxy.cloudify_proxy_plugin.tasks.wait_for_state
          inputs:
            state:
              default: 'terminated'
            timeout:
              default: 15

relationships:
  cloudify.relationships.connected_to_proxy:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: proxy.deployments.tasks.get_outputs
