plugins:
  proxy:
    executor: central_deployment_agent
    source: https://github.com/cloudify-examples/cloudify-proxy-plugin/archive/master.zip

node_types:

  cloudify.nodes.DeploymentProxy:
    derived_from: cloudify.nodes.Root
    properties:
      deployment_id:
        default: ''
        description: The deployment to build proxy object from.
      inherit_outputs:
        default: []
        description: A list of proxy deployment outputs to inherit.
      timeout:
        default: 30
        description: The time to wait for deployment executions to finish.
      inherit_inputs:
        default: False
        description: Flag that indicated if it is necessary to inherit deployment inputs.
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: proxy.deployments.tasks.wait_for_deployment
        start:
          implementation: proxy.deployments.tasks.inherit_deployment_attributes
        stop:
          implementation: proxy.deployments.tasks.cleanup
      cloudify.interfaces.validation:
          creation:
              implementation: proxy.deployments.tasks.create_validation
