plugins:

  cfy_util:
    executor: central_deployment_agent
    source: https://github.com/cloudify-incubator/cloudify-proxy-plugin/archive/v1.0.0.zip

  keys:
    executor: central_deployment_agent
    source: https://github.com/cloudify-incubator/cloudify-key-plugin/archive/v1.0.0.zip

data_types:

  cloudify.datatypes.Deployment:
    properties:
      deployment_id:
        description: >
          This is the deployment that the node is a proxy to.
        required: false
      outputs:
        description: >
          A dictionary of "{ key: value, key: value }".
          Get "key" the deployment.
          Set "value" runtime property to the value of the output.
        required: false
      unvalidated:
        default: {}

  cloudify.datatypes.BlueprintDeployment:
    properties:
      application_file_name:
        description: >
          This is the name of the blueprint.yaml file.
        default: blueprint.yaml
      blueprint_archive:
        description: >
          The URL of a .zip to upload to the manager.
        required: false
      blueprint_id:
        description: >
          The blueprint ID.
          If it already exists it will be used. 
          Defaults to node instance ID.        
        required: false
      deployment_id:
        description: >
          This is the deployment to install from the blueprint.
          If it already exists it will be used. 
          Will be generated if not provided.
        required: false
      inputs:
        description: >
          The inputs to the deployment.
        default: {}
      install_timeout:
        description: >
          How long to wait for the install workflow to exist.
        default: 180

  cloudify.datatypes.key:
    properties:
      private_key_path:
        type: string
        required: false
      public_key_path:
        type: string
        default: '~/.ssh/id_rsa.pub'
      algorithm:
        type: string
        default: 'RSA'
      bits:
        type: integer
        default: 2048
      comment:
        type: string
        required: false
      passphrase:
        type: string
        required: false
      OpenSSH_format:
        type: boolean
        required: false
      unvalidated:
        description: Unvalidated parameters.
        required: false

node_types:

  cloudify.nodes.DeploymentProxy:
    derived_from: cloudify.nodes.Root
    properties:
      use_external_resource:
        type: boolean
        default: true
      resource_config:
        type: cloudify.datatypes.Deployment
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.wait_for_deployment_ready
        start:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.query_deployment_data

  cloudify.nodes.DeploymentProxy.Compute:
    derived_from: cloudify.nodes.Compute
    properties:
      use_external_resource:
        type: boolean
        default: true
      resource_config:
        type: cloudify.datatypes.Deployment
        default: {}
      agent_config:
        default:
          install_method: none
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.wait_for_deployment_ready
        start:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.query_deployment_data

  cloudify.nodes.BlueprintDeployment:
    derived_from: cloudify.nodes.Root
    properties:
      resource_config:
        type: cloudify.datatypes.BlueprintDeployment
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.upload_blueprint
        configure:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.create_deployment
        start:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.execute_start
          inputs:
            workflow_id:
              default: install
        stop:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.execute_start
          inputs:
            workflow_id:
              default: uninstall
        delete:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.delete_deployment

  cloudify.keys.nodes.RSAKey:
    derived_from: cloudify.nodes.Root
    properties:
      use_secret_store:
        type: boolean
        default: true
      key_name:
        type: string
        required: false
        description: >
          If use_secret_store is true the key is stored in secret store by that name.
          Else, the name is deployment_id-instance_id.
      resource_config:
        description: >
          A dictionary of values to pass to configure the key.
        type: cloudify.datatypes.key
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: keys.cloudify_ssh_key.operations.create
          inputs:
            args:
              default: {}
        delete:
          implementation: keys.cloudify_ssh_key.operations.delete
          inputs:
            args:
              default: {}
