plugins:

  cfy_util:
    executor: central_deployment_agent
    package_name: cloudify_deployment_proxy

  keys:
    executor: central_deployment_agent
    package_name: cloudify_ssh_key

  configuration:
    executor: central_deployment_agent
    package_name: cloudify_configuration

  terminal:
    executor: central_deployment_agent
    package_name: cloudify_terminal

data_types:

  cloudify.datatypes.Blueprint:
    properties:
      id:
        description: >
          This is the blueprint that the deployment node is a proxy to.
        required: false
      main_file_name:
        description: >
          The application blueprint filename. If the blueprint consists many imported files this is the main blueprint.
        default: blueprint.yaml
      blueprint_archive:
        description: >
          The URL of a .zip to upload to the manager.
        required: true
      unvalidated:
        default: {}

  cloudify.datatypes.Deployment:
    properties:
      id:
        description: >
          This is the deployment that the node is a proxy to.
        required: false
      inputs:
        description: >
          The inputs to the deployment.
        default: {}
      outputs:
        description: >
          A dictionary of "{ key: value, key: value }".
          Get "key" the deployment.
          Set "value" runtime property to the value of the output.
        required: false
      logs:
        description: >
          Logs redirect settings, by default {redirect: true}
        required: false
      unvalidated:
        default: {}

  cloudify.datatypes.Node:
    properties:
      id:
        type: string

  cloudify.datatypes.NodeInstance:
    properties:
      node:
        type: cloudify.datatypes.Node
        required: false
      id:
        type: string
        required: false

  cloudify.datatypes.DeploymentProxy:
    properties:
      blueprint:
        type: cloudify.datatypes.Blueprint
        required: true
      deployment:
        type: cloudify.datatypes.Deployment
        required: true

  cloudify.datatypes.NodeInstanceProxy:
    properties:
      blueprint:
        type: cloudify.datatypes.Blueprint
        required: true
      deployment:
        type: cloudify.datatypes.Deployment
        required: true
      node_instance:
        type: cloudify.datatypes.NodeInstance

  cloudify.datatypes.key:
    properties:
      private_key_path:
        type: string
        required: false
      public_key_path:
        type: string
        default: '~/.ssh/id_rsa.pub'
      algorithm:
        type: string
        default: 'RSA'
      bits:
        type: integer
        default: 2048
      comment:
        type: string
        required: false
      passphrase:
        type: string
        required: false
      openssh_format:
        type: boolean
        required: false
      unvalidated:
        description: Unvalidated parameters.
        required: false

node_types:

  cloudify.terminal.raw:
    derived_from: cloudify.nodes.Root
    properties:
      terminal_auth:
        # login credentials for ios server
        default:
          # ssh user
          user: ""
          # optional, ssh password
          password: ""
          # optional, device ip
          ip: ""
          # optional, ssh user key
          key_content: ""
          # optional, ssh port
          port: 22
          # optional, save communication logs
          store_logs: false
          # optional, list of prompts accepted from device, by default: #/$
          promt_check: []
          # optional, list of possible errors without new line
          errors: []
          # optional, command for close connection, default 'exit'
          exit_command: exit

    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
        configure:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
        start:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
        stop:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
        delete:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}

  configuration_loader:
    derived_from: cloudify.nodes.ApplicationServer
    properties:
      parameters_json:
        default: ''
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: configuration.cloudify_configuration.tasks.load_configuration
          inputs:
            parameters:
              default: { get_property: [SELF, parameters_json] }

  cloudify.nodes.DeploymentProxy:
    derived_from: cloudify.nodes.Root
    properties:
      resource_config:
        type: cloudify.datatypes.DeploymentProxy
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.upload_blueprint
        configure:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.create_deployment
        start:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.execute_start
          inputs:
            workflow_id:
              default: install
        stop:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.execute_start
          inputs:
            workflow_id:
              default: uninstall
        delete:
          implementation: cfy_util.cloudify_deployment_proxy.tasks.delete_deployment

  cloudify.nodes.NodeInstanceProxy:
    derived_from: cloudify.nodes.DeploymentProxy
    properties:
      resource_config:
        type: cloudify.datatypes.NodeInstanceProxy
        default: {}

  cloudify.keys.nodes.RSAKey:
    derived_from: cloudify.nodes.Root
    properties:
      use_secret_store:
        type: boolean
        default: true
      key_name:
        type: string
        required: false
        description: >
          If use_secret_store is true the key is stored in secret store by that name.
          Else, the name is deployment_id-instance_id.
      resource_config:
        description: >
          A dictionary of values to pass to configure the key.
        type: cloudify.datatypes.key
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: keys.cloudify_ssh_key.operations.create
          inputs:
            store_public_key_material:
              description: >
                Allow the public key material to be stored as a runtime property. Recommended.
              type: boolean
              default: true
            store_private_key_material:
              description: Allow the private key material to be stored as a runtime property. Not recommended for manager deployments.
              type: boolean
              default: false
        delete:
          implementation: keys.cloudify_ssh_key.operations.delete

relationships:

  load_from_config:
    derived_from: cloudify.relationships.depends_on
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: configuration.cloudify_configuration.tasks.load_configuration_to_runtime_properties
          inputs:
            source_config:
              default: { get_attribute: [TARGET , params ]  }

workflows:

  configuration_update:
    mapping: configuration.cloudify_configuration.tasks.update
    parameters:
      params:
        description: json string
      configuration_node_type:
        default: configuration_loader
      node_types_to_update:
        default:
          - juniper_node_config
          - fortinet_vnf_type
