version: 2.1

job-post-steps: &job-post-steps
  post-steps:
   - slack/notify_failed

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  node: cloudify/public-unittest-orb@volatile
  wagonorb: cloudify/wagon-bulder-orb@volatile
  releaseorb: cloudify/release-orb@volatile
  managerorb: cloudify/manager-orb@volatile
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:

  cloudify-machine-py3:
    machine:
      image: ubuntu-2004:202201-02

commands:

  setup_manager:
    steps:
      - run: |
          if [[ -z "${CLOUDIFY_HOST}" ]]; then
              exit 1
          fi
      - run: |
          if [[ -z "${CLOUDIFY_TENANT}" ]] && [ -z "${CIRCLE_PROJECT_REPONAME}" ]; then
              exit 1
          fi
      - run: |
          if [[ -z "${CLOUDIFY_TOKEN}" ]]; then
              exit 1
          fi
      - run: |
          response=$(curl --write-out '%{http_code}' --silent --insecure --header "Tenant: ${CLOUDIFY_TENANT}" --header "Authentication-Token: ${CLOUDIFY_TOKEN}" https://$CLOUDIFY_HOST/api/v3.1/status --output /dev/null)
          if [[ $response != 200 ]]; then
              echo "Failed to get manager status";
              exit 1
          fi
      - run: pip3 install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/refs/heads/master.zip
      - run: git submodule update --init --recursive --remote

  prepare_test_manager:
    steps:
      - run: ecosystem-test prepare-remote-test-manager -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn*)  ~/project/plugin.yaml

  run_cloudinit_test:
    steps:
      - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/utilities-examples/cloudify_cloudinit/simple.yaml --test-id=cloudify_cloudinit --on-failure=uninstall-force

  run_ssh_key_test:
    steps:
      - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/utilities-examples/cloudify_ssh_key/create-secret-agent-key.yaml --test-id=cloudify_ssh_key --on-failure=uninstall-force

  run_secrets_test:
      steps:
        - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/utilities-examples/cloudify_secrets/write-secret-blueprint.yaml --test-id=cloudify_secrets --on-failure=uninstall-force

  run_rest_test:
      steps:
        - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/utilities-examples/cloudify_rest/example-github-status.yaml --test-id=cloudify_rest --on-failure=uninstall-force

jobs:

  integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_cloudinit_test
      - run_ssh_key_test
      - run_secrets_test
      - run_rest_test

workflows:
  version: 2
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - plugins-inputs
          # <<: *unittest-post-steps
      - node/validate_version_job
      - node/validate_documentation_job

      - wagonorb/wagon
      - wagonorb/wagon_311

      # - wagonorb/wagon:
      #     filters:
      #       branches:
      #         only: /([0-9\.]*\-build|master|dev)/
      # - wagonorb/wagon_311:
      #     filters:
      #       branches:
      #         only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - integration_tests_py3:
          context: 
            - plugins-inputs
          # <<: *job-post-steps
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
          # filters:
          #   branches:
          #     only: /([0-9\.]*\-build|master|dev)/
      - releaseorb/release:
          filters:
            branches:
              only: /master/
          requires:
            - node/unittests_job
            - wagonorb/rhel_wagon
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/wagon_311
            - node/validate_version_job
            - node/validate_documentation_job
            - integration_tests_py3

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,1,3,5"
        filters:
          branches:
            only:
              - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - plugins-inputs
          # <<: *unittest-post-steps
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/wagon_311:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - integration_tests_py3:
          context: 
            - plugins-inputs
          # <<: *job-post-steps
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
