tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/5.1.0/types.yaml
  - plugin:cloudify-utilities-plugin?version= >=1.24.0


inputs:


node_templates:

  node_one:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        start: 
          implementation: resources/install_fail.py
          executor: central_deployment_agent
        stop: 
          implementation: resources/uninstall_fail.py
          executor: central_deployment_agent
    relationships:   
      - type: cloudify.relationships.depends_on
        target: node_three       

  node_two:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create: 
          implementation: resources/install_fail.py
          executor: central_deployment_agent
        stop: 
          implementation: resources/uninstall_fail.py
          executor: central_deployment_agent
        delete:
          implementation: resources/uninstall_fail.py
          executor: central_deployment_agent      
    relationships:   
      - type: cloudify.relationships.depends_on
        target: node_three       

  node_three:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        start: 
          implementation: resources/install.py
          executor: central_deployment_agent
        stop: 
          implementation: resources/uninstall.py
          executor: central_deployment_agent
        delete: 
          implementation: resources/uninstall.py
          executor: central_deployment_agent
        postdelete: 
          implementation: resources/uninstall.py
          executor: central_deployment_agent
